### ISSUE TITLE
Dashboard Details

### ISSUE THREAD

**Issue by ralampay** [Gab13y/QuotationSystem#9]
Dashboard should include the following:
* Top 5 pending bills
* Latest edited order
* Late orders (to be compared to current time)

@kathleenlogmao please include other details as needed.

**Comment by Gab13y** [comment]
dashboard ng admin po ba sir o user sir

On Thu, Jan 29, 2015 at 3:03 PM, ralampay <notifications@github.com> wrote:

> Dashboard should include the following:
>
>    - Top 5 pending bills
>    - Latest edited order
>    - Late orders (to be compared to current time)
>
> @kathleenlogmao <https://github.com/kathleenlogmao> please include other
> details as needed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Gab13y/QuotationSystem/issues/9>.
>



-- 
Gabby Peneyra

**Comment by ralampay** [comment]
Sa user 'to. Main application.
